### PR TITLE
rename bin to match plugin API

### PR DESCRIPTION
**Pull request by drnic**
Also includes fix to install_deps.sh which requires vendor/logstash

### CODE REVIEW

**Comment by mrdavidlaing** [comment]
@drnic I'm going to hold off on merging this, since we're still discussing (internally) how an addon repo like this should be structured.

I'll carry your preference for:
1.  Using sub-modules to pull in `vendor/logsearch-filters-common`
2.  Placing logstash.conf into `target/logstash`

Into the conversation

**Comment by drnic** [comment]
It's not a preference; just one solution. Happy for any solution that makes
them all look/feel the same so we can automate them in
logsearch-boshworkspace's Rakefile.

On Wed, Feb 25, 2015 at 2:05 AM, David Laing notifications@github.com
wrote:

> @drnic https://github.com/drnic I'm going to hold off on merging this,
> since we're still discussing (internally) how an addon repo like this
> should be structured.
> 
> I'll carry your preference for:
> 1. Using sub-modules to pull in vendor/logsearch-filters-common
> 2. Placing logstash.conf into target/logstash
> 
> Into the conversation
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/logsearch/logsearch-for-websites/pull/4#issuecomment-75934888
> .

## 

Dr Nic Williams
Stark & Wayne LLC - consultancy for Cloud Foundry users
http://drnicwilliams.com
http://starkandwayne.com
cell +1 (415) 860-2185
twitter @drnic

**Comment by drnic** [comment]
Perhaps if you do holistically change how the plugins filesystem works you
could also update
https://github.com/cloudfoundry-community/logsearch-boshworkspace/blob/master/Rakefile
?

**Comment by mrdavidlaing** [comment]
@drnic - I think we'll end up adding some additional stuff to a `logsearch-for-XXX` addon (eg Kibana dashboards); standardising the folder names and perhaps adding some grouping folders.  I think these will result in very minor (or no) changes to said Rakefile.

Poke me if/when I break your stuff and I'll submit a PR to fix it :)

**Comment by drnic** [comment]
Diversity of name/git url of the plugins shouldn't be an issue. How they
look/behave internally - and if they are consistent, and if they can be
composed into a single logsearch deployment - is what we're all searching
for :)

**Pull request closed without merging**
